##yml文件未知原因无法生效
## WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
##是否启用StatFilter默认值false
#spring:
#  datasource:
#    druid:
#      web-stat-filter:
#        enabled: true
#        url-pattern: /*
#        exclusions: *.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
#      stat-view-servlet:
#        enabled: true
#        url-pattern: /durid/*
#        reset-enable: true
#        login-username: admin
#        login-password: admin